### ISSUE TITLE
old-style O horizons not parsed correcly

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/parse-osd#12]
See [KLAWASI](https://casoilresource.lawr.ucdavis.edu/sde/?series=klawasi) for an example. The bottom depths are missed entirely (`NA`) and hz-fixing logic attempts to correct by adding 1cm to the converted depths. The bottom depths are missed because of the inconsistent use of depth / units. 

From initial parsing:
|name | top| bottom|
|:----|---:|------:|
|A    |   0|      5|
|AB   |   5|     10|
|2C   |  10|     36|
|2Cf  |  36|     61|
|Oi   |  23|     NA|
|Oe   |  10|     NA|

Returned by `soilDB::fetchKSSL`:
|id      | top| bottom|hzname |
|:-------|---:|------:|:------|
|KLAWASI |   0|      5|A      |
|KLAWASI |   5|     10|AB     |
|KLAWASI |  10|     11|Oe     |
|KLAWASI |  10|     36|2C     |
|KLAWASI |  23|     24|Oi     |
|KLAWASI |  36|     61|2Cf    |

**Comment by brownag** [comment]
Recent relevant demo https://github.com/ncss-tech/aqp/pull/223.

Describes a method for accumulating depths to "fix" old style O. Function has not been incorporated into {aqp} but would be relevant to post-processing the tabular results from the OSD parsing tools to be developed in ncss-tech/SoilKnowledgeBase#25

This means that SKB may need to add aqp as an import. Which would be fine and probably useful for some further downstream products.

**Comment by dylanbeaudette** [comment]
Not going to pursue this kind of "fixing", instead focusing on the identification and assignment of OSD-correction tasks to the regions.

**Comment by brownag** [comment]
I agree that doing it generically without keeping record of where changes are made/need to be made is probably not the best. 

From my view the value to the fixing the JSON horizon results is the ability to possibly provide the correct values as supplementary info along with the flag that says it need to be corrected. This could include conversion from inches->cm at the correct time, and before reordering such that it doesn't get corrupted.
